name: terra
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pytorch=2.4
  - pytorch-cuda=12.4
  - numpy=1.26
  - pyyaml=6.0
  - matplotlib=3.8
  - pillow=10.2
  - xarray=2024.2
  - tqdm=4.66
  - pip
  - pip:
      - einops==0.7.0
      - timm==0.9.16
      - pytest>=8.0
